"""baseline: full schema

Revision ID: 7ea4c4dc5fca
Revises: 
Create Date: 2026-08-02 16:16:14.502086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea4c4dc5fca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('active_listings', sa.Integer(), nullable=True),
    sa.Column('closed_sales', sa.Integer(), nullable=True),
    sa.Column('avg_dom', sa.Integer(), nullable=True),
    sa.Column('list_to_sale', sa.Float(), nullable=True),
    sa.Column('absorption_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_trends_zip_code'), 'market_trends', ['zip_code'], unique=False)
    op.create_index('ix_trend_zip_date', 'market_trends', ['zip_code', 'snapshot_date'], unique=False)
    op.create_table('neighborhoods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('neighborhood_name', sa.String(length=200), nullable=True),
    sa.Column('median_home_price', sa.Float(), nullable=True),
    sa.Column('median_price_sqft', sa.Float(), nullable=True),
    sa.Column('avg_days_on_market', sa.Integer(), nullable=True),
    sa.Column('inventory_count', sa.Integer(), nullable=True),
    sa.Column('months_of_supply', sa.Float(), nullable=True),
    sa.Column('price_change_yoy', sa.Float(), nullable=True),
    sa.Column('price_change_mom', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('median_income', sa.Float(), nullable=True),
    sa.Column('median_age', sa.Float(), nullable=True),
    sa.Column('owner_occupied_pct', sa.Float(), nullable=True),
    sa.Column('renter_occupied_pct', sa.Float(), nullable=True),
    sa.Column('avg_school_rating', sa.Float(), nullable=True),
    sa.Column('walk_score', sa.Integer(), nullable=True),
    sa.Column('transit_score', sa.Integer(), nullable=True),
    sa.Column('restaurant_score', sa.Integer(), nullable=True),
    sa.Column('park_count', sa.Integer(), nullable=True),
    sa.Column('new_permits_ytd', sa.Integer(), nullable=True),
    sa.Column('adu_permits_ytd', sa.Integer(), nullable=True),
    sa.Column('commercial_vacancy', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neighborhoods_zip_code'), 'neighborhoods', ['zip_code'], unique=False)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_saved', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_secs', sa.Float(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'ANALYST', 'CLIENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('parcel_number', sa.String(length=50), nullable=True),
    sa.Column('property_type', sa.Enum('SINGLE_FAMILY', 'MULTI_FAMILY', 'CONDO', 'TOWNHOUSE', 'COMMERCIAL', 'MIXED_USE', 'VACANT_LAND', 'INDUSTRIAL', name='propertytype'), nullable=False),
    sa.Column('zoning', sa.Enum('RESIDENTIAL_LOW', 'RESIDENTIAL_MEDIUM', 'RESIDENTIAL_HIGH', 'COMMERCIAL', 'COMMERCIAL_GENERAL', 'INDUSTRIAL_LIGHT', 'INDUSTRIAL_HEAVY', 'MIXED_USE', 'AGRICULTURAL', 'OPEN_SPACE', 'UNKNOWN', name='zoningtype'), nullable=False),
    sa.Column('lot_size_sqft', sa.Float(), nullable=True),
    sa.Column('building_sqft', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('stories', sa.Integer(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('garage_spaces', sa.Integer(), nullable=True),
    sa.Column('pool', sa.Boolean(), nullable=True),
    sa.Column('last_sale_price', sa.Float(), nullable=True),
    sa.Column('last_sale_date', sa.DateTime(), nullable=True),
    sa.Column('assessed_value', sa.Float(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('price_per_sqft', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcel_number')
    )
    op.create_index('ix_prop_city', 'properties', ['city'], unique=False)
    op.create_index('ix_prop_location', 'properties', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_prop_zip', 'properties', ['zip_code'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_sqft', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_history_prop_date', 'price_history', ['property_id', 'date'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PLANNING', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELED', name='projectstatus'), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('spent', sa.Float(), nullable=True),
    sa.Column('estimated_value_add', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('target_end_date', sa.DateTime(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('lot_to_building_ratio', sa.Float(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('price_per_sqft', sa.Float(), nullable=True),
    sa.Column('walk_score', sa.Integer(), nullable=True),
    sa.Column('transit_score', sa.Integer(), nullable=True),
    sa.Column('bike_score', sa.Integer(), nullable=True),
    sa.Column('median_income', sa.Float(), nullable=True),
    sa.Column('crime_index', sa.Float(), nullable=True),
    sa.Column('school_rating', sa.Float(), nullable=True),
    sa.Column('distance_to_downtown_mi', sa.Float(), nullable=True),
    sa.Column('distance_to_transit_mi', sa.Float(), nullable=True),
    sa.Column('flood_zone', sa.String(length=10), nullable=True),
    sa.Column('fire_hazard_zone', sa.String(length=20), nullable=True),
    sa.Column('max_allowed_units', sa.Integer(), nullable=True),
    sa.Column('far_ratio', sa.Float(), nullable=True),
    sa.Column('setback_front_ft', sa.Float(), nullable=True),
    sa.Column('setback_rear_ft', sa.Float(), nullable=True),
    sa.Column('height_limit_ft', sa.Float(), nullable=True),
    sa.Column('adu_eligible', sa.Boolean(), nullable=True),
    sa.Column('adu_max_sqft', sa.Integer(), nullable=True),
    sa.Column('development_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.create_table('property_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('model_type', sa.String(length=30), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('value_lower_bound', sa.Float(), nullable=True),
    sa.Column('value_upper_bound', sa.Float(), nullable=True),
    sa.Column('recommended_additions', sa.JSON(), nullable=True),
    sa.Column('development_potential', sa.JSON(), nullable=True),
    sa.Column('roi_projections', sa.JSON(), nullable=True),
    sa.Column('feature_importances', sa.JSON(), nullable=True),
    sa.Column('top_value_drives', sa.JSON(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_valuation_prop_model', 'property_valuations', ['property_id', 'model_name'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', name='taskstatus'), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_hrs', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('milestones')
    op.drop_index('ix_valuation_prop_model', table_name='property_valuations')
    op.drop_table('property_valuations')
    op.drop_table('property_features')
    op.drop_table('projects')
    op.drop_index('ix_price_history_prop_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('ix_prop_zip', table_name='properties')
    op.drop_index('ix_prop_location', table_name='properties')
    op.drop_index('ix_prop_city', table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scrape_jobs')
    op.drop_index(op.f('ix_neighborhoods_zip_code'), table_name='neighborhoods')
    op.drop_table('neighborhoods')
    op.drop_index('ix_trend_zip_date', table_name='market_trends')
    op.drop_index(op.f('ix_market_trends_zip_code'), table_name='market_trends')
    op.drop_table('market_trends')
    # ### end Alembic commands ###
